### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by praven07** [NordlingDev/nativescript-na-camera#6]
Can I use this with angular nativescript?

**Comment by NordlingArt** [comment]
I have never tried Angular in NativeScript, so unfortunately I cannot answer that question as of now. You are free to try and post the results whether it works with Angular or not.

**Comment by nadeemmar** [comment]
I am quite the noob when it comes to NativeScript but after a bit of reading and trial and error, I was able to get it to work. Here is what you need to do:

In your module, register custom element NACamera

`import * as elementRegistryModule from 'nativescript-angular/element-registry';
elementRegistryModule.registerElement("NACamera", () => require("nativescript-na-camera").Camera);`

In your UI, use the following tag name "NACamera". Note that NACamera:Camera is not required since we directly registered the Camera object which has the view above.

`<NACamera id="cameraPreview"></NACamera>`

in your component TS or JS code, you can use the plugin as described in the demo:

`const NACamera = require("nativescript-na-camera"); NACamera.start()` 

and so on. 

@NordlingArt Thanks for the wonderful plugin, perhaps these instructions can be added to the ReadMe?
